### ISSUE TITLE
Ruby Core?

### ISSUE THREAD

**Issue by parkr** [djberg96/win32-file#7]
Hey @djberg96! I'm one of the maintainers of Jekyll, a popular static site generator that powers GitHub Pages. We have received many complaints from Windows users over the years and have begun making more of an effort to support Windows. It seems Ruby core has many bugs on Windows and they don't seem to get fixed as far as I can tell.  One of the issues we are noticing (because we do lots of I/O) is improper handling of files. I found a link to this project on a bug filed and summarily closed on bugs.ruby-lang.org and we're evaluating it now to see if it fixes our issues handling symlinks (https://github.com/jekyll/jekyll/pull/5374).

Do you know whether these patches are included in Ruby core? If not, do you know why not? Is there anything I can do?

Thanks!

**Comment by djberg96** [comment]
I gave up long ago on the ruby-core team. Historically they've used Linux, and so that is their first priority in any given release. They do put some effort into MS Windows, but it has always been a second class citizen IMO.

They can't really integrate win32/file into Ruby since it depends on ffi, so that would require integrating another lib into their standard library. That said, I think ffi *should* be integrated into the standard library, but that's another issue.
